name: Discord Message Sender

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Select random message
        id: select-message
        run: |
          node -e "
          const fs = require('fs');
          const messages = JSON.parse(fs.readFileSync('messages.json', 'utf8'));
          const randomIndex = Math.floor(Math.random() * messages.length);
          console.log(`::set-output name=message::${messages[randomIndex]}`);
          "
          
      - name: Send message to Discord
        env:
          WEBHOOK_URL: ${{ secrets.WHL }}
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"${{ steps.select-message.outputs.message }}\", \"username\": \"Blobby\", \"avatar_url\": \"https://raw.githubusercontent.com/SCPNerd/troll/main/pfp.png\"}" \
               $WEBHOOK_URL
