name: Discord Message Sender

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Send message to Discord
        env:
          WEBHOOK_URL: ${{ secrets.WHL }}
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"Your message here\", \"username\": \"Blobby\", \"avatar_url\": \"https://raw.githubusercontent.com/SCPNerd/troll/main/pfp.png\"}" \
               $WEBHOOK_URL
