name: Send Random Discord Message

on:
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Select Random Message
        id: select_message
        run: |
          messages=$(jq -r '.[]' messages.json)
          count=$(echo "$messages" | wc -l)
          random_index=$((RANDOM % count))
          selected_message=$(echo "$messages" | sed -n "$((random_index + 1))p")
          echo "message=$selected_message" >> $GITHUB_OUTPUT

      - name: Send Discord Message
        uses: tsickert/discord-webhook@v1.0.0
        with:
          webhook-url: ${{ secrets.WHL }}
          content: ${{ steps.select_message.outputs.message }}
          username: "Blobby"
          avatar-url: "https://raw.githubusercontent.com/SCPNerd/troll/ce590fc324c3e7c7a2bfe7fd0869a2248c7e844b/pfp.png"
